<?php
/**
 * Copyright (c) 2013 Hawksearch (www.hawksearch.com) - All Rights Reserved
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
 * PARTICULAR PURPOSE.
 */
?>
<script type="text/javascript">
	//<![CDATA[

	var hawkSearchTimestamp = {
		isInit : false,
		buttonId : null,
		init : function() {
			this.url = '<?php echo $this->getClearUrl() ?>';
			this.buttonId = '<?php echo $this->getButtonId()?>';
			this.displayId = "hawksearch_display_msg";
			this.isInit = true;
		},
		clear : function() {
			var r = confirm("Clearing the timestamp will cause the next feed generation to produce a full result set. Are you sure you want to continue?");
			if(r != true) {
				return;
			}
			if (!this.isInit) {
				this.init();
			}
			new Ajax.Request(this.url, {
				onSuccess: function(transport) {
					var response = transport.responseText.evalJSON();
					this.displayResults(response);
				}.bind(this)
			});
		},
		displayResults : function(response) {
			if(response.error) {
				alert(response.error);
				return;
			}
			var lastGen = $('hawksearch_lastgen_time');
			lastGen.innerHTML = response.lastGen;
			$(this.buttonId).disabled = true;
			$(this.buttonId).addClassName("disabled");

			/*
						var responseEl = $(this.displayId);
						if (responseEl == null) {
							var responseEl = new Element('p', {id : this.displayId}).addClassName('note');
							Element.insert($(this.buttonId) , {after: responseEl});
						}
						if (response.error) {
							return responseEl.innerHTML = response.error;
						}
						$(this.buttonId).disabled = true;
						$(this.buttonId).addClassName("disabled");
						return responseEl.innerHTML = "<?php echo Mage::getModel('hawksearch_datafeed/feed')->getAjaxNotice(); ?>";
*/
		}
	}

	//]]>
</script>